create table auth.auth_user
(
    id         integer generated by default as identity
        primary key,
    first_name varchar                                       not null,
    last_name  varchar                                       not null,
    email      varchar                                       not null
        unique
        constraint check_valid_email
            check ((email)::text ~* '^[a-z][a-z0-9]{2,30}@\w{4,10}.\w{2,3}$'::text),
    password   text                                          not null
        constraint check_valid_password
            check (password ~* '^(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&])[a-z\d@$!%*#?&]{4,}$'::text),
    role       auth.auth_role default 'USER'::auth.auth_role not null,
    balance    numeric(10, 1) default 0
        constraint check_user_account
            check (balance >= (0)::numeric)
);

alter table auth.auth_user
    owner to postgres;

