create table category.category
(
    id   integer generated by default as identity
        primary key,
    name varchar not null
        unique
);

alter table category.category
    owner to postgres;

