create table product.product
(
    id          integer generated by default as identity
        primary key,
    name        varchar        not null,
    price       numeric(10, 2) not null,
    quantity    integer        not null,
    category_id integer        not null
        references category.category
);

alter table product.product
    owner to postgres;

