create table transaction.transactions
(
    id                 integer generated by default as identity,
    created_at         timestamp default CURRENT_TIMESTAMP not null,
    product_id         integer                             not null
        references product.product,
    user_id            integer                             not null
        references auth.auth_user,
    quantity_purchased integer                             not null,
    total_price        numeric(10, 2)
);

alter table transaction.transactions
    owner to postgres;

